# Generated by Django 4.1.1 on 2022-09-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecard', '0003_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='style',
        ),
        migrations.AddField(
            model_name='style',
            name='border',
            field=models.CharField(choices=[('solid', 'SOLID'), ('dotted', 'DOTTED'), ('ridge', 'RIDGE'), ('double', 'DOUBLE'), ('groove', 'GROOVE')], default='solid', max_length=6),
        ),
        migrations.AddField(
            model_name='style',
            name='border_color',
            field=models.CharField(choices=[('white', 'WHITE'), ('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('black', 'BLACK'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('orange', 'ORANGE')], default='white', max_length=6),
        ),
        migrations.AddField(
            model_name='style',
            name='card_color',
            field=models.CharField(choices=[('white', 'WHITE'), ('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('black', 'BLACK'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('orange', 'ORANGE')], default='white', max_length=6),
        ),
        migrations.AddField(
            model_name='style',
            name='font',
            field=models.CharField(choices=[('lobster', 'LOBSTER'), ('papyrus', 'PAPYRUS'), ('comic_sans', 'COMIC_SANS')], default='lobster', max_length=10),
        ),
        migrations.AddField(
            model_name='style',
            name='font_color',
            field=models.CharField(choices=[('white', 'WHITE'), ('red', 'RED'), ('yellow', 'YELLOW'), ('green', 'GREEN'), ('blue', 'BLUE'), ('black', 'BLACK'), ('pink', 'PINK'), ('purple', 'PURPLE'), ('orange', 'ORANGE')], default='black', max_length=6),
        ),
        migrations.AddField(
            model_name='style',
            name='text_align',
            field=models.CharField(choices=[('left', 'LEFT'), ('center', 'CENTER'), ('right', 'RIGHT')], default='left', max_length=6),
        ),
    ]
